project_name: gcloc
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: 'app/gcloc/main.go'
    binary: gcloc
    ldflags:
      - -s -w
      - -X github.com/Scorpio69t/gcloc/cmd.Version={{.Version}}
      - -X github.com/Scorpio69t/gcloc/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/Scorpio69t/gcloc/cmd.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm64"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
